common:
  httpAddress: ":10005"
  serverName: "ai-dating"


mongo:
  address: "mongodb://localhost:27017/wooplus?retryWrites=true"
  maxPoolSize: 10

redis:
  address: "localhost:3306"
  maxPoolSize: 10 # 线程池大小


openAi:
  secret: ""
  url: "https://api.openai.com/v1/chat/completions"